language: go

go:
    - stable
    - 1.12.x

sudo: required
dist: xenial

go_import_path: github.com/teranos/honeytrap

services:
    - docker

os:
    - linux

env:
    - GIMME_OS=linux GIMME_ARCH=amd64 GO111MODULE=on

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y software-properties-common python-software-properties
    - go get github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/tcnksm/ghr
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin

install:
    - go get -v github.com/teranos/honeytrap

script:
    - go build .
